# Generated by Django 5.0.6 on 2024-06-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
