# Generated by Django 4.2.11 on 2024-05-27 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_ws_user_groups_ws_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ws_user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ws_user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='ws_user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
