# Generated by Django 5.0.6 on 2024-06-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_ws_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
