# Generated by Django 5.0.6 on 2024-06-04 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_delete_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professoravailability',
            old_name='available_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='professoravailability',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
